"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import CustomerShell from "@/components/layout/CustomerShell";
import { checkoutSchema, type CheckoutValues } from "@/lib/validations";
import { useCart } from "@/lib/cart-store";
import PriceBreakdown from "@/components/customer/PriceBreakdown";
import { orderService } from "@/lib/services/order.service";

export default function CheckoutPage() {
  const router=useRouter(); const {items,total,clear}=useCart(); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const {register,handleSubmit,formState:{errors}}=useForm<CheckoutValues>({resolver:zodResolver(checkoutSchema),defaultValues:{delivery:"home",payment:"cod"}});
  const submit=async(v:CheckoutValues)=>{if(!items.length){setError("Your cart is empty.");return;}setLoading(true);setError("");try{const subtotal=total();const order={id:`o-${Date.now()}`,orderNumber:`CK-${Date.now().toString().slice(-6)}`,restaurantId:items[0].restaurantId,restaurantName:"Aai's Kitchen",items:items.map(x=>({id:x.id,name:x.name,quantity:x.quantity,price:x.price})),subtotal,deliveryFee:v.delivery==="home"?30:0,total:subtotal+(v.delivery==="home"?30:0),status:"pending" as const,customerName:v.name,phone:v.phone,address:v.address,landmark:v.landmark,deliveryRequested:v.delivery==="home",createdAt:new Date().toISOString()};await orderService.create(order);clear();router.push(`/orders/${order.id}`);}catch(e){setError(e instanceof Error?e.message:"Unable to place order");}finally{setLoading(false);}};
  return <CustomerShell><div className="container-kitchen py-10"><h1 className="text-4xl font-black text-[#6b4f3a]">Checkout</h1><form onSubmit={handleSubmit(submit)} className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="card-kitchen p-5 sm:p-7"><h2 className="text-xl font-black">Delivery details</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-bold">Customer name<input className="input-kitchen mt-1" {...register("name")}/>{errors.name&&<span className="text-xs text-[#b33b21]">{errors.name.message}</span>}</label><label className="text-sm font-bold">Phone<input className="input-kitchen mt-1" inputMode="numeric" {...register("phone")}/>{errors.phone&&<span className="text-xs text-[#b33b21]">{errors.phone.message}</span>}</label><label className="text-sm font-bold">Landmark<input className="input-kitchen mt-1" {...register("landmark")}/></label><label className="sm:col-span-2 text-sm font-bold">Address<textarea className="input-kitchen mt-1 min-h-28" {...register("address")}/>{errors.address&&<span className="text-xs text-[#b33b21]">{errors.address.message}</span>}</label></div><h2 className="mt-8 text-xl font-black">Delivery option</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="rounded-2xl border p-4"><input type="radio" value="home" {...register("delivery")}/> <b className="ml-2">Home Delivery</b><p className="ml-6 text-sm text-[#6d625a]">Request local delivery</p></label><label className="rounded-2xl border p-4"><input type="radio" value="pickup" {...register("delivery")}/> <b className="ml-2">Pickup</b><p className="ml-6 text-sm text-[#6d625a]">Collect from kitchen</p></label></div><h2 className="mt-8 text-xl font-black">Payment</h2><label className="mt-3 block rounded-2xl border p-4"><input type="radio" value="cod" {...register("payment")}/> <b className="ml-2">Cash on delivery / pickup</b><p className="ml-6 text-sm text-[#6d625a]">Payment placeholder for prototype</p></label>{error&&<div className="mt-5 rounded-xl bg-[#f8e6e1] p-3 text-sm font-semibold text-[#b33b21]">{error}</div>}</section><aside className="card-kitchen h-fit p-5"><h2 className="text-xl font-black">Order summary</h2><div className="mt-4 space-y-2 text-sm">{items.map(x=><div key={x.id} className="flex justify-between"><span>{x.name} × {x.quantity}</span><span>{x.price*x.quantity}</span></div>)}</div><div className="mt-5"><PriceBreakdown subtotal={total()} deliveryFee={30}/></div><button disabled={loading} className="btn-primary mt-6 w-full disabled:opacity-60">{loading?"Placing order…":"Place order"}</button></aside></form></div></CustomerShell>;
}
