"use client";
import { useEffect, useState } from "react";
import CustomerShell from "@/components/layout/CustomerShell";
import OrderStatusStepper from "@/components/customer/OrderStatusStepper";
import StatusBadge from "@/components/ui/StatusBadge";
import { orderService } from "@/lib/services/order.service";
import type { Order } from "@/types/order";
import { money } from "@/lib/utils";
import { Phone, MessageCircle } from "lucide-react";
export default function OrderDetailPage(){const [order,setOrder]=useState<Order|null>(null);const [loading,setLoading]=useState(true);const id=location.pathname.split("/").pop()!;useEffect(()=>{orderService.getById(id).then(setOrder).finally(()=>setLoading(false))},[id]);if(loading)return <CustomerShell><div className="container-kitchen py-16">Loading order…</div></CustomerShell>;if(!order)return <CustomerShell><div className="container-kitchen py-16">Order not found.</div></CustomerShell>;return <CustomerShell><div className="container-kitchen py-10"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-sm font-bold text-[#6d625a]">{order.orderNumber}</p><h1 className="text-3xl font-black text-[#6b4f3a]">{order.restaurantName}</h1></div><StatusBadge status={order.status}/></div><section className="card-kitchen mt-7 p-5 sm:p-7"><h2 className="text-xl font-black">Order status</h2><div className="mt-6"><OrderStatusStepper status={order.status}/></div>{order.deliveryRequested&&<div className="mt-6 rounded-2xl bg-[#e8f3e3] p-4 text-sm font-bold text-[#5c8d47]">Delivery requested — a local delivery contact will coordinate your drop-off.</div>}</section><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="card-kitchen p-5"><h2 className="text-xl font-black">Items</h2>{order.items.map(i=><div key={i.id} className="flex justify-between border-b py-3 text-sm"><span>{i.name} × {i.quantity}</span><b>{money(i.price*i.quantity)}</b></div>)}<div className="flex justify-between pt-4 font-black"><span>Total</span><span>{money(order.total)}</span></div></section><section className="card-kitchen p-5"><h2 className="text-xl font-black">Delivery</h2><p className="mt-3 text-sm"><b>Address:</b> {order.address}</p>{order.landmark&&<p className="mt-1 text-sm"><b>Landmark:</b> {order.landmark}</p>}<div className="mt-5 flex gap-2"><a href={`tel:${order.phone}`} className="btn-primary"><Phone size={16}/> Call</a><button className="btn-secondary"><MessageCircle size={16}/> Contact delivery</button></div></section></div></div></CustomerShell>}
